/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description 健康探針：證明套件 import + 設定載入（不含祕密）。
         *
         *     暴露兩條路徑：``/healthz``（本地 / in-process）與 ``/health``。Cloud Run 的
         *     Google Front End 會**攔截 `/healthz`**（在抵達容器前回自家 404），故雲端可達的
         *     探針走 ``/health``（runbook §5）。
         */
        get: operations["healthz_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description 健康探針：證明套件 import + 設定載入（不含祕密）。
         *
         *     暴露兩條路徑：``/healthz``（本地 / in-process）與 ``/health``。Cloud Run 的
         *     Google Front End 會**攔截 `/healthz`**（在抵達容器前回自家 404），故雲端可達的
         *     探針走 ``/health``（runbook §5）。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description 跑 5 節點 workflow，回帶引用 + 合規狀態 + 每節點 trace 的答案。
         *
         *     ``viewer`` 透傳進 workflow state（issue #32）：retriever 依此做 owner-scoped 過濾。
         */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Research
         * @description 跑 Deep Research ReAct loop（≤6 迴圈 / ≥3 引用 / 過合規），回結論 + 證據 + 步驟。
         *
         *     ``viewer`` 透傳進 run_deep_research（issue #32）：R4 真實 search fn 接入後
         *     可依此做 owner-scoped 過濾；stub_search 無 owner 欄位，目前為 no-op。
         */
        post: operations["research_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notifications
         * @description 收件匣列表（created_at 倒序）+ 未讀數 + 外送降級記錄。
         */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Event
         * @description 發布事件進**真實管線**（去重→接地→合規閘門→訂閱→digest/派送）。
         *
         *     壞事件回 ``status=rejected``（HTTP 200——拒收是管線的正常 outcome，
         *     不是傳輸層錯誤；生產者依 ``status`` 分支）。
         */
        post: operations["publish_event_notifications_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Notification Read
         * @description 標已讀；查無該通知 → 404。``read_at`` 取 API 邊界當下時間
         *     （確定性約束只管管線內部；牆鐘是邊界輸入，同事件 ``occurred_at`` 的角色）。
         */
        post: operations["mark_notification_read_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Notifications
         * @description 重置為全新收件匣（in-memory 單例換新；demo / 測試隔離用）。
         */
        post: operations["reset_notifications_notifications_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Notifications Demo
         * @description 互動 demo 頁：收件匣 UI/UX + 事件模擬器（吃同源 /notifications 端點）。
         */
        get: operations["notifications_demo_demo_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts
         * @description 跑 mock MOPS 事件集 → WatchdogAlert 陣列（token-free fallback，CI 可測）。
         *
         *     R7 Alert Inbox 直接消費本端點；severity 上色、blocked 標紅。
         *     無 Gemini 金鑰時 Watchdog 走確定性 fallback（token=0）。
         */
        get: operations["alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertResponse
         * @description R7 Alert Inbox 契約（docs/R7_frontend_開工指南.md §2c）。欄位名一字不差。
         */
        AlertResponse: {
            /** Event Id */
            event_id: string;
            /** Ticker */
            ticker: string;
            /** Summary */
            summary: string;
            /** Compliance Status */
            compliance_status: string;
            /** Severity */
            severity: string;
            /** Evidence */
            evidence: components["schemas"]["Citation"][];
        };
        /** AskRequest */
        AskRequest: {
            /**
             * Query
             * @description 自然語言問題
             */
            query: string;
            /**
             * Viewer
             * @description 存取控制身分（issue #32）
             * @default __public__
             */
            viewer: string;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Compliance Status */
            compliance_status: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Trace */
            trace: components["schemas"]["NodeTrace"][];
        };
        /**
         * Citation
         * @description 引用單筆紀錄。W1 D1 stub mode 用 origin='stub'；後續週次擴展。
         */
        Citation: {
            /**
             * Source Id
             * @description 來源識別（頁碼 hash / URL hash / stub-id）
             */
            source_id: string;
            /**
             * Snippet
             * @description 被引用的原文片段
             */
            snippet: string;
            /**
             * Origin
             * @description 檢索來源；W1 固定 'stub'
             * @enum {string}
             */
            origin: "stub" | "bm25" | "embedding" | "colpali" | "rerank" | "news";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NodeTrace
         * @description 單次節點執行紀錄，由 @traced 裝飾器 emit。
         */
        NodeTrace: {
            /** Node Name */
            node_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error" | "skipped";
            /** Input Keys */
            input_keys?: string[];
            /** Output Keys */
            output_keys?: string[];
            /** Error Message */
            error_message?: string | null;
            /**
             * Elapsed Ms
             * @description wall-clock 毫秒，不可為負
             */
            elapsed_ms: number;
        };
        /**
         * Notification
         * @description 管線組裝後、可派送的標準通知（spec FR-NC-001）。
         */
        Notification: {
            /** Notification Id */
            notification_id: string;
            /**
             * Event Id
             * @description 來源事件識別碼（digest 時為首筆）
             */
            event_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "watchdog_alert" | "watchlist_event" | "data_ingested" | "research_done" | "contradiction" | "pipeline_health" | "ops_alert" | "compliance_incident";
            /**
             * Audience
             * @enum {string}
             */
            audience: "user" | "internal";
            /** Ticker */
            ticker?: string | null;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "watch" | "alert";
            /** Evidence */
            evidence?: components["schemas"]["Citation"][];
            /**
             * Deep Link
             * @default
             */
            deep_link: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at?: string | null;
            /**
             * Compliance Status
             * @enum {string}
             */
            compliance_status: "passed" | "blocked" | "skipped";
            /**
             * Digest Count
             * @default 1
             */
            digest_count: number;
        };
        /** NotificationListResponse */
        NotificationListResponse: {
            /** Items */
            items: components["schemas"]["Notification"][];
            /** Unread Count */
            unread_count: number;
            /** Delivery Failures */
            delivery_failures: string[];
        };
        /**
         * PublishOutcome
         * @description ``publish()`` 回傳（contracts/notification-pipeline.md）。
         */
        PublishOutcome: {
            /**
             * Status
             * @enum {string}
             */
            status: "delivered" | "deduped" | "digested" | "blocked" | "rejected" | "filtered";
            notification?: components["schemas"]["Notification"] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * ReActStep
         * @description 單一 ReAct 步：推理 + 行動 + 觀察（逐步可溯源審計）。
         */
        ReActStep: {
            /** Thought */
            thought: string;
            /** Action */
            action: string;
            /**
             * Action Input
             * @default
             */
            action_input: string;
            /**
             * Observation
             * @default
             */
            observation: string;
        };
        /** ResearchRequest */
        ResearchRequest: {
            /**
             * Question
             * @description 開放式研究問題
             */
            question: string;
            /**
             * Viewer
             * @description 存取控制身分（issue #32）
             * @default __public__
             */
            viewer: string;
        };
        /** ResearchResponse */
        ResearchResponse: {
            /** Final Answer */
            final_answer: string;
            /** Evidence */
            evidence: components["schemas"]["Citation"][];
            /** React Steps */
            react_steps: components["schemas"]["ReActStep"][];
            /** Status */
            status: string;
            /** Compliance Status */
            compliance_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_event_notifications_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_notifications_notifications_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    notifications_demo_demo_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    alerts_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"][];
                };
            };
        };
    };
}
